server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/user/**

            - id: device-service
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/api/v1/device/**

            - id: ingestion-service
              uri: lb://INGESTION-SERVICE
              predicates:
                - Path=/api/v1/ingestion/**

            - id: usage-service
              uri: lb://USAGE-SERVICE
              predicates:
                - Path=/api/v1/usage

            - id: alert-service
              uri: lb://ALERT-SERVICE
              predicates:
                - Path=/api/v1/alert

            - id: insight-service
              uri: lb://INSIGHT-SERVICE
              predicates:
                - Path=/api/v1/insight

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/