spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-learn
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
        starttls.enable: false