server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    hikari:
      schema: microservices_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS microservices_schema
      connection-timeout: 10000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgresSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/