server:
  port: 8083

spring:
  application:
    name: usage-service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: usage-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/microservices-system

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8091/realms/microservices-system
            user-name-attribute: preferred_username

        registration:
          keycloak:
            provider: keycloak
            client-id: usage-service
            client-secret: TQoYikeRlAFMLOB6MeLGkeBQbCcBxJsa
            authorization-grant-type: client_credentials
            scope:
              - openid
              - microprofile-jwt
              - user:read
              - device:read:any

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

app:
  influx:
    url: http://localhost:8072
    token: admin-token
    org: microservice-learn
    bucket: usage-bucket

  client:
    device-url: http://localhost:8081/api/v1/device
    user-url: http://localhost:8080/api/v1/user

  consumption-interval: 3