server:
  port: 8083

spring:
  application:
    name: usage-service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: usage-service

app:
  influx:
    url: http://localhost:8072
    token: admin-token
    org: microservice-learn
    bucket: usage-bucket