spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-learn?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/microservices-system

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8091/realms/microservices-system
            user-name-attribute: preferred_username

        registration:
          keycloak:
            provider: keycloak
            client-id: device-service
            client-secret: guwl94Mnwsah2vFYx3R21IZG3BeF4Fu6
            authorization-grant-type: client_credentials
            scope:
              - openid
              - microprofile-jwt
              - user:read

app:
  clients:
    user:
      base-url: http://localhost:9000/api/v1/user